# Generated by Django 3.0.8 on 2020-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_auto_20200708_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=1000),
        ),
    ]
